<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>$schema</key>
	<string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
	<key>fileTypes</key>
	<array>
		<string>cue</string>
	</array>
	<key>name</key>
	<string>CUE</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#whitespace</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.package</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.namespace</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;![\p{L}\p{Nd}_\$\#])(package)[ \t]+([\p{L}\$\#][\p{L}\p{Nd}_\$\#]*)(?![\p{L}\p{Nd}_\$\#])</string>
		</dict>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;![\p{L}\p{Nd}_\$\#])(import)[ \t]+(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.import</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.parens.begin</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.parens.end</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.imports</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#whitespace</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.namespace</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.begin</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>string.quoted.double-import</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>punctuation.colon</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>entity.name</string>
								</dict>
								<key>6</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.end</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?:([\p{L}\$\#][\p{L}\p{Nd}_\$\#]*)[ \t]+)?(")([^:"]+)(?:(:)([\p{L}\$\#][\p{L}\p{Nd}_\$\#]*))?(")</string>
							<key>name</key>
							<string>meta.import-spec</string>
						</dict>
						<dict>
							<key>match</key>
							<string>;</string>
							<key>name</key>
							<string>punctuation.separator</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#invalid_in_parens</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.import</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.namespace</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double-import</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.colon</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>entity.name</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;![\p{L}\p{Nd}_\$\#])(import)[ \t]+(?:([\p{L}\$\#][\p{L}\p{Nd}_\$\#]*)[ \t]+)?(")([^:"]+)(?:(:)([\p{L}\$\#][\p{L}\p{Nd}_\$\#]*))?(")</string>
					<key>name</key>
					<string>meta.import</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#punctuation_comma</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#declaration</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#invalid_in_braces</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>attribute_element</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([\p{L}\$\#][\p{L}\p{Nd}_\$\#]*|_[\p{L}\p{Nd}_\$\#]+)(=)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.bind</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=[,\)])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#attribute_string</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([\p{L}\$\#][\p{L}\p{Nd}_\$\#]*|_[\p{L}\p{Nd}_\$\#]+)(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.attribute-elements.begin</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.attribute-elements.end</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#punctuation_comma</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#attribute_element</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute_string</string>
				</dict>
			</array>
		</dict>
		<key>attribute_string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^\n,"'#=\(\)]+</string>
					<key>name</key>
					<string>string.unquoted</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^,\)]+</string>
					<key>name</key>
					<string>invalid</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(//).*$\n?</string>
					<key>name</key>
					<string>comment.line</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block</string>
				</dict>
			</array>
		</dict>
		<key>declaration</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(@)([\p{L}\$\#][\p{L}\p{Nd}_\$\#]*|_[\p{L}\p{Nd}_\$\#]+)(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.annotation</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.annotation</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.attribute-elements.begin</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.attribute-elements.end</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.annotation</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#punctuation_comma</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#attribute_element</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!:)::(?!:)</string>
					<key>name</key>
					<string>punctuation.isa</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#punctuation_colon</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\?</string>
					<key>name</key>
					<string>punctuation.option</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;![=!&gt;&lt;])=(?![=~])</string>
					<key>name</key>
					<string>punctuation.bind</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&lt;-</string>
					<key>name</key>
					<string>punctuation.arrow</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<key>expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.control.for</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>variable.other</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>variable.other</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>keyword.control.in</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?&lt;![\p{L}\p{Nd}_\$\#])(for)[ \t]+([\p{L}\$\#][\p{L}\p{Nd}_\$\#]*|_[\p{L}\p{Nd}_\$\#]+)(?:[ \t]*(,)[ \t]*([\p{L}\$\#][\p{L}\p{Nd}_\$\#]*|_[\p{L}\p{Nd}_\$\#]+))?[ \t]+(in)(?![\p{L}\p{Nd}_\$\#])</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?&lt;![\p{L}\p{Nd}_\$\#])if(?![\p{L}\p{Nd}_\$\#])</string>
							<key>name</key>
							<string>keyword.control.conditional</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.control.let</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>variable.other</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.bind</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?&lt;![\p{L}\p{Nd}_\$\#])(let)[ \t]+([\p{L}\$\#][\p{L}\p{Nd}_\$\#]*|_[\p{L}\p{Nd}_\$\#]+)[ \t]*(=)(?![=])</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>[\+\-\*]|/(?![/*])</string>
							<key>name</key>
							<string>keyword.operator</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?&lt;![\p{L}\p{Nd}_\$\#])(?:div|mod|quo|rem)(?![\p{L}\p{Nd}_\$\#])</string>
							<key>name</key>
							<string>keyword.operator.word</string>
						</dict>
						<dict>
							<key>match</key>
							<string>=[=~]|![=~]|&lt;=|&gt;=|[&lt;](?![-=])|[&gt;](?![=])</string>
							<key>name</key>
							<string>keyword.operator.comparison</string>
						</dict>
						<dict>
							<key>match</key>
							<string>&amp;{2}|\|{2}|!(?![=~])</string>
							<key>name</key>
							<string>keyword.operator.logical</string>
						</dict>
						<dict>
							<key>match</key>
							<string>&amp;(?!&amp;)|\|(?!\|)</string>
							<key>name</key>
							<string>keyword.operator.set</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.accessor</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.member</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;!\.)(\.)([\p{L}\$\#][\p{L}\p{Nd}_\$\#]*|_[\p{L}\p{Nd}_\$\#]+)(?![\p{L}\p{Nd}_\$\#])</string>
				</dict>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?&lt;![\p{L}\p{Nd}_\$\#])_(?!\|)(?![\p{L}\p{Nd}_\$\#])</string>
							<key>name</key>
							<string>constant.language.top</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?&lt;![\p{L}\p{Nd}_\$\#])_\|_(?![\p{L}\p{Nd}_\$\#])</string>
							<key>name</key>
							<string>constant.language.bottom</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?&lt;![\p{L}\p{Nd}_\$\#])null(?![\p{L}\p{Nd}_\$\#])</string>
							<key>name</key>
							<string>constant.language.null</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?&lt;![\p{L}\p{Nd}_\$\#])(?:true|false)(?![\p{L}\p{Nd}_\$\#])</string>
							<key>name</key>
							<string>constant.language.bool</string>
						</dict>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>match</key>
											<string>(?&lt;![\p{L}\p{Nd}_\.])[0-9](?:_?[0-9])*\.(?:[0-9](?:_?[0-9])*)?(?:[eE][\+\-]?[0-9](?:_?[0-9])*)?(?![\p{L}\p{Nd}_\.])</string>
											<key>name</key>
											<string>constant.numeric.float.decimal</string>
										</dict>
										<dict>
											<key>match</key>
											<string>(?&lt;![\p{L}\p{Nd}_\.])[0-9](?:_?[0-9])*[eE][\+\-]?[0-9](?:_?[0-9])*(?![\p{L}\p{Nd}_\.])</string>
											<key>name</key>
											<string>constant.numeric.float.decimal</string>
										</dict>
										<dict>
											<key>match</key>
											<string>(?&lt;![\p{L}\p{Nd}_\.])\.[0-9](?:_?[0-9])*(?:[eE][\+\-]?[0-9](?:_?[0-9])*)?(?![\p{L}\p{Nd}_\.])</string>
											<key>name</key>
											<string>constant.numeric.float.decimal</string>
										</dict>
									</array>
								</dict>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>patterns</key>
											<array>
												<dict>
													<key>match</key>
													<string>(?&lt;![\p{L}\p{Nd}_\.])(?:0|[1-9](?:_?[0-9])*)(?:\.[0-9](?:_?[0-9])*)?(?:[KMGTPEYZ]i?)(?![\p{L}\p{Nd}_\.])</string>
													<key>name</key>
													<string>constant.numeric.integer.other</string>
												</dict>
												<dict>
													<key>match</key>
													<string>(?&lt;![\p{L}\p{Nd}_\.])\.[0-9](?:_?[0-9])*(?:[KMGTPEYZ]i?)(?![\p{L}\p{Nd}_\.])</string>
													<key>name</key>
													<string>constant.numeric.integer.other</string>
												</dict>
											</array>
										</dict>
										<dict>
											<key>match</key>
											<string>(?&lt;![\p{L}\p{Nd}_\.])(?:0|[1-9](?:_?[0-9])*)(?![\p{L}\p{Nd}_\.])</string>
											<key>name</key>
											<string>constant.numeric.integer.decimal</string>
										</dict>
										<dict>
											<key>match</key>
											<string>(?&lt;![\p{L}\p{Nd}_\.])0b[0-1](?:_?[0-1])*(?![\p{L}\p{Nd}_\.])</string>
											<key>name</key>
											<string>constant.numeric.integer.binary</string>
										</dict>
										<dict>
											<key>match</key>
											<string>(?&lt;![\p{L}\p{Nd}_\.])0[xX][0-9a-fA-F](?:_?[0-9a-fA-F])*(?![\p{L}\p{Nd}_\.])</string>
											<key>name</key>
											<string>constant.numeric.integer.hexadecimal</string>
										</dict>
										<dict>
											<key>match</key>
											<string>(?&lt;![\p{L}\p{Nd}_\.])0o?[0-7](?:_?[0-7])*(?![\p{L}\p{Nd}_\.])</string>
											<key>name</key>
											<string>constant.numeric.integer.octal</string>
										</dict>
									</array>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?&lt;![\p{L}\p{Nd}_\$\#])(?:bool|u?int(?:8|16|32|64|128)?|float(?:32|64)?|string|bytes|number|rune)(?![\p{L}\p{Nd}_\$\#])</string>
							<key>name</key>
							<string>support.type</string>
						</dict>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>begin</key>
									<string>(?&lt;![\p{L}\p{Nd}_\$\#])(len|close|and|or)(\()</string>
									<key>beginCaptures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>support.function</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>punctuation.section.parens.begin</string>
										</dict>
									</dict>
									<key>end</key>
									<string>\)</string>
									<key>endCaptures</key>
									<dict>
										<key>0</key>
										<dict>
											<key>name</key>
											<string>punctuation.section.parens.end</string>
										</dict>
									</dict>
									<key>name</key>
									<string>meta.function-call</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#whitespace</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#comment</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#punctuation_comma</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#expression</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#invalid_in_parens</string>
										</dict>
									</array>
								</dict>
								<dict>
									<key>begin</key>
									<string>(?&lt;![\p{L}\p{Nd}_\$\#])([\p{L}\$\#][\p{L}\p{Nd}_\$\#]*)(\.)(\p{Lu}[\p{L}\p{Nd}_\$\#]*)(\()</string>
									<key>beginCaptures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>support.module</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>punctuation</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>support.function</string>
										</dict>
										<key>4</key>
										<dict>
											<key>name</key>
											<string>punctuation.section.parens.begin</string>
										</dict>
									</dict>
									<key>end</key>
									<string>\)</string>
									<key>endCaptures</key>
									<dict>
										<key>0</key>
										<dict>
											<key>name</key>
											<string>punctuation.section.parens.end</string>
										</dict>
									</dict>
									<key>name</key>
									<string>meta.function-call</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#whitespace</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#comment</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#punctuation_comma</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#expression</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#invalid_in_parens</string>
										</dict>
									</array>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>(?&lt;![\p{L}\p{Nd}_\$\#])(?:[\p{L}\$\#][\p{L}\p{Nd}_\$\#]*|_[\p{L}\p{Nd}_\$\#]+)(?![\p{L}\p{Nd}_\$\#])</string>
							<key>name</key>
							<string>variable.other</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\{</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.struct.begin</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\}</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.struct.end</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.struct</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#whitespace</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#comment</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#punctuation_comma</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#punctuation_ellipsis</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#declaration</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#invalid_in_braces</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>\[</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.brackets.begin</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\]</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.brackets.end</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.brackets</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#whitespace</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#comment</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#punctuation_colon</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#punctuation_comma</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#punctuation_ellipsis</string>
								</dict>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>variable.other</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>punctuation.alias</string>
										</dict>
									</dict>
									<key>match</key>
									<string>([\p{L}\$\#][\p{L}\p{Nd}_\$\#]*|_[\p{L}\p{Nd}_\$\#]+)[ \t]*(=)</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#expression</string>
								</dict>
								<dict>
									<key>match</key>
									<string>[^\]]+</string>
									<key>name</key>
									<string>invalid</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>\(</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.parens.begin</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\)</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.parens.end</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.parens</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#whitespace</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#comment</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#punctuation_comma</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#expression</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#invalid_in_parens</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>invalid_in_braces</key>
		<dict>
			<key>match</key>
			<string>[^\}]+</string>
			<key>name</key>
			<string>invalid</string>
		</dict>
		<key>invalid_in_parens</key>
		<dict>
			<key>match</key>
			<string>[^\)]+</string>
			<key>name</key>
			<string>invalid</string>
		</dict>
		<key>punctuation_colon</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!:):(?!:)</string>
			<key>name</key>
			<string>punctuation.colon</string>
		</dict>
		<key>punctuation_comma</key>
		<dict>
			<key>match</key>
			<string>,</string>
			<key>name</key>
			<string>punctuation.separator</string>
		</dict>
		<key>punctuation_ellipsis</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.)\.{3}(?!\.)</string>
			<key>name</key>
			<string>punctuation.ellipsis</string>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>#"""</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>string.quoted.double-multiline</string>
					<key>end</key>
					<string>"""#</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.string</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\#(?:"""|/|\\|[abfnrtv]|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})</string>
							<key>name</key>
							<string>constant.character.escape</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\#(?:[0-7]{3}|x[0-9A-Fa-f]{2})</string>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\\#\(</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.interpolation.begin</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>source.cue.embedded</string>
							<key>end</key>
							<string>\)</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.interpolation.end</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.interpolation</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#whitespace</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#expression</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#invalid_in_parens</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>\\#.</string>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>#"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>string.quoted.double</string>
					<key>end</key>
					<string>"#</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.string</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\#(?:"|/|\\|[abfnrtv]|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})</string>
							<key>name</key>
							<string>constant.character.escape</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\#(?:[0-7]{3}|x[0-9A-Fa-f]{2})</string>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\\#\(</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.interpolation.begin</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>source.cue.embedded</string>
							<key>end</key>
							<string>\)</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.interpolation.end</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.interpolation</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#whitespace</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#expression</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#invalid_in_parens</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>\\#.</string>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>#'''</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>string.quoted.single-multiline</string>
					<key>end</key>
					<string>'''#</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.string</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\#(?:'''|/|\\|[abfnrtv]|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})</string>
							<key>name</key>
							<string>constant.character.escape</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\#(?:[0-7]{3}|x[0-9A-Fa-f]{2})</string>
							<key>name</key>
							<string>constant.character.escape</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\\#\(</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.interpolation.begin</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>source.cue.embedded</string>
							<key>end</key>
							<string>\)</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.interpolation.end</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.interpolation</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#whitespace</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#expression</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#invalid_in_parens</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>\\#.</string>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>#'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>string.quoted.single</string>
					<key>end</key>
					<string>'#</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.string</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\#(?:'|/|\\|[abfnrtv]|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})</string>
							<key>name</key>
							<string>constant.character.escape</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\#(?:[0-7]{3}|x[0-9A-Fa-f]{2})</string>
							<key>name</key>
							<string>constant.character.escape</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\\#\(</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.interpolation.begin</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>source.cue.embedded</string>
							<key>end</key>
							<string>\)</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.interpolation.end</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.interpolation</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#whitespace</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#expression</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#invalid_in_parens</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>\\#.</string>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"""</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>string.quoted.double-multiline</string>
					<key>end</key>
					<string>"""</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.string</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\(?:"""|/|\\|[abfnrtv]|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})</string>
							<key>name</key>
							<string>constant.character.escape</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\(?:[0-7]{3}|x[0-9A-Fa-f]{2})</string>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\\\(</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.interpolation.begin</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>source.cue.embedded</string>
							<key>end</key>
							<string>\)</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.interpolation.end</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.interpolation</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#whitespace</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#expression</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#invalid_in_parens</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>string.quoted.double</string>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.string</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\(?:"|/|\\|[abfnrtv]|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})</string>
							<key>name</key>
							<string>constant.character.escape</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\(?:[0-7]{3}|x[0-9A-Fa-f]{2})</string>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\\\(</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.interpolation.begin</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>source.cue.embedded</string>
							<key>end</key>
							<string>\)</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.interpolation.end</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.interpolation</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#whitespace</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#expression</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#invalid_in_parens</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'''</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>string.quoted.single-multiline</string>
					<key>end</key>
					<string>'''</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.string</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\(?:'''|/|\\|[abfnrtv]|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})</string>
							<key>name</key>
							<string>constant.character.escape</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\(?:[0-7]{3}|x[0-9A-Fa-f]{2})</string>
							<key>name</key>
							<string>constant.character.escape</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\\\(</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.interpolation.begin</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>source.cue.embedded</string>
							<key>end</key>
							<string>\)</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.interpolation.end</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.interpolation</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#whitespace</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#expression</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#invalid_in_parens</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>string.quoted.single</string>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.string</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\(?:'|/|\\|[abfnrtv]|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})</string>
							<key>name</key>
							<string>constant.character.escape</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\(?:[0-7]{3}|x[0-9A-Fa-f]{2})</string>
							<key>name</key>
							<string>constant.character.escape</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\\\(</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.interpolation.begin</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>source.cue.embedded</string>
							<key>end</key>
							<string>\)</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.interpolation.end</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.interpolation</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#whitespace</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#expression</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#invalid_in_parens</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>`</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>string.quoted.backtick</string>
					<key>end</key>
					<string>`</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.string</string>
				</dict>
			</array>
		</dict>
		<key>whitespace</key>
		<dict>
			<key>match</key>
			<string>[ \t\r\n]+</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.cue</string>
</dict>
</plist>
